version: 2.1

orbs:
  node: circleci/node@5.0.2
  browser-tools: circleci/browser-tools@1.1.0

jobs:
  lint:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run lint
          name: Lint Files
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  test-e2e:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test-e2e
          name: E2E Tests
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run Unit Tests
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  sass:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run sass
          name: Compile SCSS
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  tsc:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run tsc
          name: Compile TypeScript
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run webpack
          name: Build project with Webpack
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  test_wiki:
    jobs:
      - lint
      - test
      - sass
      - tsc
      - build
