"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.STONE_FACED_PAGE_ID = exports.DR_WEED_PAGE_ID = exports.MELVIN_GERRITSEN_PAGE_ID = exports.ACHILLES_PAGE_ID = exports.REGGIE_KING_PAGE_ID = exports.RUSSEL_KING_PAGE_ID = exports.HOME_PAGE_ID = void 0;
exports.HOME_PAGE_ID = 'home_page';
exports.RUSSEL_KING_PAGE_ID = 'russel_king';
exports.REGGIE_KING_PAGE_ID = 'reggie_king';
exports.ACHILLES_PAGE_ID = 'achilles';
exports.MELVIN_GERRITSEN_PAGE_ID = 'melvin_gerritsen';
exports.DR_WEED_PAGE_ID = 'dr_weed';
exports.STONE_FACED_PAGE_ID = 'stone_faced';
